<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLSET80F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLSET80F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLSET80F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLSET80F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLSET80F\App_KernelDevDebugContainer([
    'container.build_hash' => 'LSET80F',
    'container.build_id' => '917f6350',
    'container.build_time' => 1582214074,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLSET80F');
