<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2r57xDx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2r57xDx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2r57xDx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2r57xDx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2r57xDx\App_KernelDevDebugContainer([
    'container.build_hash' => '2r57xDx',
    'container.build_id' => 'aa04f959',
    'container.build_time' => 1582247013,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2r57xDx');
