<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC6hSaES\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC6hSaES/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC6hSaES.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC6hSaES\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC6hSaES\App_KernelDevDebugContainer([
    'container.build_hash' => 'C6hSaES',
    'container.build_id' => '0414ab14',
    'container.build_time' => 1582247842,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC6hSaES');
