<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL8BcNak\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL8BcNak/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL8BcNak.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL8BcNak\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL8BcNak\App_KernelDevDebugContainer([
    'container.build_hash' => 'L8BcNak',
    'container.build_id' => '87566c14',
    'container.build_time' => 1582209244,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL8BcNak');
